name: Deploy WebApp

on:
  push:
    branches:
      - Website

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_PASSWORD: ${{secrets.DB_PASSWORD}}
          MYSQL_USERNAME: ${{secrets.DB_USERNAME}}
          MYSQL_DATABASE: ${{secrets.DB_SERVER}}
        ports:
          - 3306
    steps:
      - uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "uni-project-sgc" #Must be unique in Heroku
          heroku_email: "14093239@shrewsbury.ac.uk"
          